// Dizionario statico mood → traduzioni per lingua.
// I mood di Musixmatch sono un insieme finito; i temi sono frasi comuni.
// Fallback: stringa originale inglese.

const MOOD_MAP = {
  // ---- mood ----
  heartbreak:         { it: "cuore spezzato",   fr: "cœur brisé",            es: "desamor",               de: "Herzschmerz",          pt: "coração partido",    ja: "失恋",          ko: "실연",      zh: "心碎" },
  empowerment:        { it: "empowerment",       fr: "émancipation",          es: "empoderamiento",        de: "Ermächtigung",         pt: "empoderamento",      ja: "エンパワーメント", ko: "자기 역량 강화", zh: "赋权" },
  anger:              { it: "rabbia",            fr: "colère",                es: "rabia",                 de: "Wut",                  pt: "raiva",              ja: "怒り",          ko: "분노",      zh: "愤怒" },
  angst:              { it: "angoscia",          fr: "angoisse",              es: "angustia",              de: "Angst",                pt: "angústia",           ja: "不安",          ko: "불안",      zh: "焦虑" },
  freedom:            { it: "libertà",           fr: "liberté",               es: "libertad",              de: "Freiheit",             pt: "liberdade",          ja: "自由",          ko: "자유",      zh: "自由" },
  reflection:         { it: "riflessione",       fr: "réflexion",             es: "reflexión",             de: "Reflexion",            pt: "reflexão",           ja: "内省",          ko: "성찰",      zh: "反思" },
  despair:            { it: "disperazione",      fr: "désespoir",             es: "desesperación",         de: "Verzweiflung",         pt: "desespero",          ja: "絶望",          ko: "절망",      zh: "绝望" },
  love:               { it: "amore",             fr: "amour",                 es: "amor",                  de: "Liebe",                pt: "amor",               ja: "愛",            ko: "사랑",      zh: "爱" },
  "social commentary":{ it: "critica sociale",   fr: "commentaire social",    es: "crítica social",        de: "Gesellschaftskritik",  pt: "crítica social",     ja: "社会批評",       ko: "사회 비평",  zh: "社会评论" },
  optimism:           { it: "ottimismo",         fr: "optimisme",             es: "optimismo",             de: "Optimismus",           pt: "otimismo",           ja: "楽観主義",       ko: "낙관주의",   zh: "乐观" },
  sadness:            { it: "tristezza",         fr: "tristesse",             es: "tristeza",              de: "Traurigkeit",          pt: "tristeza",           ja: "悲しみ",         ko: "슬픔",      zh: "悲伤" },
  joy:                { it: "gioia",             fr: "joie",                  es: "alegría",               de: "Freude",               pt: "alegria",            ja: "喜び",          ko: "기쁨",      zh: "喜悦" },
  romance:            { it: "romanticismo",      fr: "romance",               es: "romance",               de: "Romantik",             pt: "romance",            ja: "ロマンス",       ko: "로맨스",     zh: "浪漫" },
  melancholy:         { it: "malinconia",        fr: "mélancolie",            es: "melancolía",            de: "Melancholie",          pt: "melancolia",         ja: "憂鬱",          ko: "우울함",     zh: "忧郁" },
  nostalgia:          { it: "nostalgia",         fr: "nostalgie",             es: "nostalgia",             de: "Nostalgie",            pt: "nostalgia",          ja: "ノスタルジア",    ko: "향수",      zh: "怀旧" },
  inspiration:        { it: "ispirazione",       fr: "inspiration",           es: "inspiración",           de: "Inspiration",          pt: "inspiração",         ja: "インスピレーション", ko: "영감",   zh: "灵感" },
  darkness:           { it: "oscurità",          fr: "obscurité",             es: "oscuridad",             de: "Dunkelheit",           pt: "escuridão",          ja: "闇",            ko: "어둠",      zh: "黑暗" },
  hope:               { it: "speranza",          fr: "espoir",                es: "esperanza",             de: "Hoffnung",             pt: "esperança",          ja: "希望",          ko: "희망",      zh: "希望" },
  rebellion:          { it: "ribellione",        fr: "rébellion",             es: "rebelión",              de: "Rebellion",            pt: "rebelião",           ja: "反乱",          ko: "반항",      zh: "反叛" },
  loneliness:         { it: "solitudine",        fr: "solitude",              es: "soledad",               de: "Einsamkeit",           pt: "solidão",            ja: "孤独",          ko: "외로움",     zh: "孤独" },
  yearning:           { it: "desiderio",         fr: "désir ardent",          es: "anhelo",                de: "Sehnsucht",            pt: "anseio",             ja: "憧れ",          ko: "그리움",     zh: "渴望" },
  vulnerability:      { it: "vulnerabilità",     fr: "vulnérabilité",         es: "vulnerabilidad",        de: "Verletzlichkeit",      pt: "vulnerabilidade",    ja: "脆さ",          ko: "취약함",     zh: "脆弱" },
  alienation:         { it: "alienazione",       fr: "aliénation",            es: "alienación",            de: "Entfremdung",          pt: "alienação",          ja: "疎外感",         ko: "소외감",     zh: "异化" },
  frustration:        { it: "frustrazione",      fr: "frustration",           es: "frustración",           de: "Frustration",          pt: "frustração",         ja: "フラストレーション", ko: "좌절",   zh: "沮丧" },
  passion:            { it: "passione",          fr: "passion",               es: "pasión",                de: "Leidenschaft",         pt: "paixão",             ja: "情熱",          ko: "열정",      zh: "激情" },
  pride:              { it: "orgoglio",          fr: "fierté",                es: "orgullo",               de: "Stolz",                pt: "orgulho",            ja: "誇り",          ko: "자부심",     zh: "骄傲" },
  resilience:         { it: "resilienza",        fr: "résilience",            es: "resiliencia",           de: "Resilienz",            pt: "resiliência",        ja: "回復力",         ko: "회복력",     zh: "韧性" },
};

const THEME_MAP = {
  // ---- temi ----
  "toxic relationships":                        { it: "relazioni tossiche",                    fr: "relations toxiques",                 es: "relaciones tóxicas",               de: "toxische Beziehungen",          pt: "relacionamentos tóxicos",       ja: "有害な関係",          ko: "독성 관계",          zh: "有毒关系" },
  "moving on":                                  { it: "andare avanti",                         fr: "tourner la page",                    es: "seguir adelante",                  de: "weitermachen",                  pt: "seguir em frente",              ja: "前に進む",            ko: "앞으로 나아가기",      zh: "继续前行" },
  "self-empowerment":                           { it: "auto-realizzazione",                    fr: "auto-émancipation",                  es: "autoempoderamiento",               de: "Selbstermächtigung",            pt: "autoempoderamento",             ja: "自己成長",            ko: "자기 역량 강화",       zh: "自我赋权" },
  "emotional dependency":                       { it: "dipendenza emotiva",                    fr: "dépendance émotionnelle",            es: "dependencia emocional",            de: "emotionale Abhängigkeit",       pt: "dependência emocional",         ja: "感情的依存",           ko: "감정적 의존",          zh: "情感依赖" },
  "betrayal and dishonesty":                    { it: "tradimento e disonestà",                fr: "trahison et malhonnêteté",           es: "traición y deshonestidad",         de: "Verrat und Unehrlichkeit",      pt: "traição e desonestidade",       ja: "裏切りと不誠実",        ko: "배신과 불성실",         zh: "背叛与不诚实" },
  "moving on and resilience":                   { it: "andare avanti e resilienza",            fr: "tourner la page et résilience",      es: "seguir adelante y resiliencia",    de: "weitermachen und Resilienz",    pt: "seguir em frente e resiliência",ja: "前進と回復力",          ko: "앞으로 나아가기와 회복력", zh: "继续前行与韧性" },
  "self-discovery and empowerment":             { it: "scoperta di sé ed empowerment",         fr: "découverte de soi et émancipation",  es: "autodescubrimiento y empoderamiento", de: "Selbstentdeckung und Ermächtigung", pt: "autodescoberta e empoderamento", ja: "自己発見と成長",      ko: "자기 발견과 역량 강화",   zh: "自我发现与赋权" },
  "historical manipulation":                    { it: "manipolazione storica",                 fr: "manipulation historique",            es: "manipulación histórica",           de: "historische Manipulation",      pt: "manipulação histórica",         ja: "歴史的操作",           ko: "역사적 조작",          zh: "历史操纵" },
  "colonial legacy":                            { it: "eredità coloniale",                     fr: "héritage colonial",                  es: "legado colonial",                  de: "kolonielles Erbe",              pt: "legado colonial",               ja: "植民地の遺産",          ko: "식민지 유산",          zh: "殖民遗产" },
  "identity and unity":                         { it: "identità e unità",                      fr: "identité et unité",                  es: "identidad y unidad",               de: "Identität und Einheit",         pt: "identidade e unidade",          ja: "アイデンティティと団結",  ko: "정체성과 단결",         zh: "身份认同与团结" },
  "resistance against oppression":              { it: "resistenza all'oppressione",            fr: "résistance contre l'oppression",     es: "resistencia a la opresión",        de: "Widerstand gegen Unterdrückung",pt: "resistência à opressão",        ja: "抑圧への抵抗",          ko: "억압에 대한 저항",       zh: "抵抗压迫" },
  "romantic love":                              { it: "amore romantico",                       fr: "amour romantique",                   es: "amor romántico",                   de: "romantische Liebe",             pt: "amor romântico",                ja: "ロマンチックな愛",       ko: "낭만적 사랑",          zh: "浪漫爱情" },
  "heartbreak":                                 { it: "cuore spezzato",                        fr: "cœur brisé",                         es: "desamor",                          de: "Herzschmerz",                   pt: "coração partido",               ja: "失恋",                ko: "실연",               zh: "心碎" },
  "friendship":                                 { it: "amicizia",                              fr: "amitié",                             es: "amistad",                          de: "Freundschaft",                  pt: "amizade",                       ja: "友情",                ko: "우정",               zh: "友情" },
  "loss":                                       { it: "perdita",                               fr: "perte",                              es: "pérdida",                          de: "Verlust",                       pt: "perda",                         ja: "喪失",                ko: "상실",               zh: "失去" },
  "redemption":                                 { it: "redenzione",                            fr: "rédemption",                         es: "redención",                        de: "Erlösung",                      pt: "redenção",                      ja: "贖罪",                ko: "구원",               zh: "救赎" },
  "fame and success":                           { it: "fama e successo",                       fr: "gloire et succès",                   es: "fama y éxito",                     de: "Ruhm und Erfolg",               pt: "fama e sucesso",                ja: "名声と成功",            ko: "명성과 성공",          zh: "名声与成功" },
  "faith and spirituality":                     { it: "fede e spiritualità",                   fr: "foi et spiritualité",                es: "fe y espiritualidad",              de: "Glaube und Spiritualität",      pt: "fé e espiritualidade",          ja: "信仰とスピリチュアリティ", ko: "믿음과 영성",          zh: "信仰与灵性" },
  "social justice":                             { it: "giustizia sociale",                     fr: "justice sociale",                    es: "justicia social",                  de: "soziale Gerechtigkeit",         pt: "justiça social",                ja: "社会正義",             ko: "사회 정의",           zh: "社会正义" },
  "mental health":                              { it: "salute mentale",                        fr: "santé mentale",                      es: "salud mental",                     de: "psychische Gesundheit",         pt: "saúde mental",                  ja: "メンタルヘルス",         ko: "정신 건강",           zh: "心理健康" },
  "addiction":                                  { it: "dipendenza",                            fr: "dépendance",                         es: "adicción",                         de: "Sucht",                         pt: "vício",                         ja: "依存症",              ko: "중독",               zh: "成瘾" },
  "family":                                     { it: "famiglia",                              fr: "famille",                            es: "familia",                          de: "Familie",                       pt: "família",                       ja: "家族",                ko: "가족",               zh: "家庭" },
  "childhood":                                  { it: "infanzia",                              fr: "enfance",                            es: "infancia",                         de: "Kindheit",                      pt: "infância",                      ja: "幼少期",              ko: "어린 시절",           zh: "童年" },
  "war":                                        { it: "guerra",                                fr: "guerre",                             es: "guerra",                           de: "Krieg",                         pt: "guerra",                        ja: "戦争",                ko: "전쟁",               zh: "战争" },
  "death":                                      { it: "morte",                                 fr: "mort",                               es: "muerte",                           de: "Tod",                           pt: "morte",                         ja: "死",                  ko: "죽음",               zh: "死亡" },
  "dreams":                                     { it: "sogni",                                 fr: "rêves",                              es: "sueños",                           de: "Träume",                        pt: "sonhos",                        ja: "夢",                  ko: "꿈",                zh: "梦想" },
  "nature":                                     { it: "natura",                                fr: "nature",                             es: "naturaleza",                       de: "Natur",                         pt: "natureza",                      ja: "自然",                ko: "자연",               zh: "自然" },
  "resilience":                                 { it: "resilienza",                            fr: "résilience",                         es: "resiliencia",                      de: "Resilienz",                     pt: "resiliência",                   ja: "回復力",              ko: "회복력",             zh: "韧性" },
  "loneliness":                                 { it: "solitudine",                            fr: "solitude",                           es: "soledad",                          de: "Einsamkeit",                    pt: "solidão",                       ja: "孤独",                ko: "외로움",             zh: "孤独" },
  "identity":                                   { it: "identità",                              fr: "identité",                           es: "identidad",                        de: "Identität",                     pt: "identidade",                    ja: "アイデンティティ",      ko: "정체성",             zh: "身份认同" },
  "self-discovery":                             { it: "scoperta di sé",                        fr: "découverte de soi",                  es: "autodescubrimiento",               de: "Selbstentdeckung",              pt: "autodescoberta",                ja: "自己発見",             ko: "자기 발견",           zh: "自我发现" },
  "betrayal":                                   { it: "tradimento",                            fr: "trahison",                           es: "traición",                         de: "Verrat",                        pt: "traição",                       ja: "裏切り",              ko: "배신",               zh: "背叛" },
  "healing":                                    { it: "guarigione",                            fr: "guérison",                           es: "sanación",                         de: "Heilung",                       pt: "cura",                          ja: "癒し",                ko: "치유",               zh: "治愈" },
  "growing up":                                 { it: "crescere",                              fr: "grandir",                            es: "crecer",                           de: "aufwachsen",                    pt: "crescer",                       ja: "成長",                ko: "성장",               zh: "成长" },
  "abuse of power":                             { it: "abuso di potere",                       fr: "abus de pouvoir",                    es: "abuso de poder",                   de: "Machtmissbrauch",               pt: "abuso de poder",                ja: "権力の乱用",            ko: "권력 남용",           zh: "权力滥用" },
  "political protest":                          { it: "protesta politica",                     fr: "protestation politique",             es: "protesta política",                de: "politischer Protest",           pt: "protesto político",             ja: "政治的抗議",            ko: "정치적 항의",          zh: "政治抗议" },
  "revolution":                                 { it: "rivoluzione",                           fr: "révolution",                         es: "revolución",                       de: "Revolution",                    pt: "revolução",                     ja: "革命",                ko: "혁명",               zh: "革命" },
  "party and celebration":                      { it: "festa e celebrazione",                  fr: "fête et célébration",                es: "fiesta y celebración",             de: "Feier und Fest",                pt: "festa e celebração",            ja: "パーティーと祝典",       ko: "파티와 축하",          zh: "派对与庆典" },
  "escapism":                                   { it: "evasione",                              fr: "évasion",                            es: "escapismo",                        de: "Eskapismus",                    pt: "escapismo",                     ja: "現実逃避",             ko: "현실 도피",           zh: "逃避现实" },
  "race and identity":                          { it: "razza e identità",                      fr: "race et identité",                   es: "raza e identidad",                 de: "Rasse und Identität",           pt: "raça e identidade",             ja: "人種とアイデンティティ",  ko: "인종과 정체성",         zh: "种族与身份" },
};

/**
 * Traduce una singola etichetta di mood o tema nella lingua indicata.
 * Prova prima MOOD_MAP poi THEME_MAP (case-insensitive).
 * Fallback: stringa originale.
 */
export function translateLabel(label, langCode) {
  if (!label || !langCode || langCode === "en") return label;
  const key = label.trim().toLowerCase();
  const entry = MOOD_MAP[key] || THEME_MAP[key];
  return (entry && entry[langCode]) || label;
}
